
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND AS CALL COMMA CREATE DISCARD DO END EQUALS EXPORT FROM GREATER GREATER_EQ IDENTIFIER IMPORT JOIN LESS LESS_EQ LIMIT LPAREN NOT_EQUALS NUMBER PRINT PROCEDURE RENAME RPAREN SELECT SEMICOLON STAR STRING TABLE USING WHEREprogram : statement SEMICOLON\n| program statement SEMICOLONstatement : import_stmt\n| export_stmt\n| discard_stmt\n| rename_stmt\n| print_stmt\n| select_stmt\n| create_select_stmt\n| create_join_stmt\n| procedure_decl\n| procedure_callimport_stmt : IMPORT TABLE IDENTIFIER FROM STRINGexport_stmt : EXPORT TABLE IDENTIFIER AS STRINGdiscard_stmt : DISCARD TABLE IDENTIFIERrename_stmt : RENAME TABLE IDENTIFIER IDENTIFIERprint_stmt : PRINT TABLE IDENTIFIERselect_stmt : SELECT select_fields FROM IDENTIFIER where_clause limit_clauseselect_fields : STAR\n| field_listfield_list : IDENTIFIER\n| field_list COMMA IDENTIFIERwhere_clause : WHERE condition_list\n| emptycondition_list : condition\n| condition_list AND conditioncondition : IDENTIFIER GREATER NUMBER\n| IDENTIFIER LESS NUMBER\n| IDENTIFIER GREATER_EQ NUMBER\n| IDENTIFIER LESS_EQ NUMBER\n| IDENTIFIER EQUALS value\n| IDENTIFIER NOT_EQUALS valuevalue : STRING\n| NUMBERlimit_clause : LIMIT NUMBER\n| emptycreate_select_stmt : CREATE TABLE IDENTIFIER select_stmtcreate_join_stmt : CREATE TABLE IDENTIFIER FROM IDENTIFIER JOIN IDENTIFIER USING LPAREN IDENTIFIER RPARENprocedure_decl : PROCEDURE IDENTIFIER DO program ENDprocedure_call : CALL IDENTIFIERempty :'
    
_lr_action_items = {'IMPORT':([0,1,23,36,45,53,],[13,13,-1,-2,13,13,]),'EXPORT':([0,1,23,36,45,53,],[14,14,-1,-2,14,14,]),'DISCARD':([0,1,23,36,45,53,],[15,15,-1,-2,15,15,]),'RENAME':([0,1,23,36,45,53,],[16,16,-1,-2,16,16,]),'PRINT':([0,1,23,36,45,53,],[17,17,-1,-2,17,17,]),'SELECT':([0,1,23,36,44,45,53,],[18,18,-1,-2,18,18,18,]),'CREATE':([0,1,23,36,45,53,],[19,19,-1,-2,19,19,]),'PROCEDURE':([0,1,23,36,45,53,],[20,20,-1,-2,20,20,]),'CALL':([0,1,23,36,45,53,],[21,21,-1,-2,21,21,]),'$end':([1,23,36,],[0,-1,-2,]),'SEMICOLON':([2,3,4,5,6,7,8,9,10,11,12,22,35,39,41,48,49,51,54,55,56,58,60,61,63,64,65,68,77,78,79,80,81,82,83,84,85,89,],[23,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,36,-40,-15,-17,-16,-41,-37,-13,-14,-41,-24,-39,-18,-36,-23,-25,-35,-26,-27,-28,-29,-30,-31,-33,-34,-32,-38,]),'TABLE':([13,14,15,16,17,19,],[24,25,26,27,28,33,]),'STAR':([18,],[31,]),'IDENTIFIER':([18,20,21,24,25,26,27,28,33,40,42,43,52,57,67,69,87,],[30,34,35,37,38,39,40,41,44,48,49,50,59,66,76,66,88,]),'END':([23,36,53,],[-1,-2,60,]),'FROM':([29,30,31,32,37,44,50,],[42,-21,-19,-20,46,52,-22,]),'COMMA':([30,32,50,],[-21,43,-22,]),'DO':([34,],[45,]),'AS':([38,],[47,]),'STRING':([46,47,74,75,],[54,55,83,83,]),'WHERE':([49,],[57,]),'LIMIT':([49,56,58,64,65,77,78,79,80,81,82,83,84,85,],[-41,62,-24,-23,-25,-26,-27,-28,-29,-30,-31,-33,-34,-32,]),'JOIN':([59,],[67,]),'NUMBER':([62,70,71,72,73,74,75,],[68,78,79,80,81,84,84,]),'AND':([64,65,77,78,79,80,81,82,83,84,85,],[69,-25,-26,-27,-28,-29,-30,-31,-33,-34,-32,]),'GREATER':([66,],[70,]),'LESS':([66,],[71,]),'GREATER_EQ':([66,],[72,]),'LESS_EQ':([66,],[73,]),'EQUALS':([66,],[74,]),'NOT_EQUALS':([66,],[75,]),'USING':([76,],[86,]),'LPAREN':([86,],[87,]),'RPAREN':([88,],[89,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,45,],[1,53,]),'statement':([0,1,45,53,],[2,22,2,22,]),'import_stmt':([0,1,45,53,],[3,3,3,3,]),'export_stmt':([0,1,45,53,],[4,4,4,4,]),'discard_stmt':([0,1,45,53,],[5,5,5,5,]),'rename_stmt':([0,1,45,53,],[6,6,6,6,]),'print_stmt':([0,1,45,53,],[7,7,7,7,]),'select_stmt':([0,1,44,45,53,],[8,8,51,8,8,]),'create_select_stmt':([0,1,45,53,],[9,9,9,9,]),'create_join_stmt':([0,1,45,53,],[10,10,10,10,]),'procedure_decl':([0,1,45,53,],[11,11,11,11,]),'procedure_call':([0,1,45,53,],[12,12,12,12,]),'select_fields':([18,],[29,]),'field_list':([18,],[32,]),'where_clause':([49,],[56,]),'empty':([49,56,],[58,63,]),'limit_clause':([56,],[61,]),'condition_list':([57,],[64,]),'condition':([57,69,],[65,77,]),'value':([74,75,],[82,85,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement SEMICOLON','program',2,'p_program','main.py',112),
  ('program -> program statement SEMICOLON','program',3,'p_program','main.py',113),
  ('statement -> import_stmt','statement',1,'p_statement','main.py',117),
  ('statement -> export_stmt','statement',1,'p_statement','main.py',118),
  ('statement -> discard_stmt','statement',1,'p_statement','main.py',119),
  ('statement -> rename_stmt','statement',1,'p_statement','main.py',120),
  ('statement -> print_stmt','statement',1,'p_statement','main.py',121),
  ('statement -> select_stmt','statement',1,'p_statement','main.py',122),
  ('statement -> create_select_stmt','statement',1,'p_statement','main.py',123),
  ('statement -> create_join_stmt','statement',1,'p_statement','main.py',124),
  ('statement -> procedure_decl','statement',1,'p_statement','main.py',125),
  ('statement -> procedure_call','statement',1,'p_statement','main.py',126),
  ('import_stmt -> IMPORT TABLE IDENTIFIER FROM STRING','import_stmt',5,'p_import_stmt','main.py',131),
  ('export_stmt -> EXPORT TABLE IDENTIFIER AS STRING','export_stmt',5,'p_export_stmt','main.py',173),
  ('discard_stmt -> DISCARD TABLE IDENTIFIER','discard_stmt',3,'p_discard_stmt','main.py',197),
  ('rename_stmt -> RENAME TABLE IDENTIFIER IDENTIFIER','rename_stmt',4,'p_rename_stmt','main.py',207),
  ('print_stmt -> PRINT TABLE IDENTIFIER','print_stmt',3,'p_print_stmt','main.py',219),
  ('select_stmt -> SELECT select_fields FROM IDENTIFIER where_clause limit_clause','select_stmt',6,'p_select_stmt','main.py',235),
  ('select_fields -> STAR','select_fields',1,'p_select_fields','main.py',288),
  ('select_fields -> field_list','select_fields',1,'p_select_fields','main.py',289),
  ('field_list -> IDENTIFIER','field_list',1,'p_field_list','main.py',296),
  ('field_list -> field_list COMMA IDENTIFIER','field_list',3,'p_field_list','main.py',297),
  ('where_clause -> WHERE condition_list','where_clause',2,'p_where_clause','main.py',304),
  ('where_clause -> empty','where_clause',1,'p_where_clause','main.py',305),
  ('condition_list -> condition','condition_list',1,'p_condition_list','main.py',312),
  ('condition_list -> condition_list AND condition','condition_list',3,'p_condition_list','main.py',313),
  ('condition -> IDENTIFIER GREATER NUMBER','condition',3,'p_condition','main.py',320),
  ('condition -> IDENTIFIER LESS NUMBER','condition',3,'p_condition','main.py',321),
  ('condition -> IDENTIFIER GREATER_EQ NUMBER','condition',3,'p_condition','main.py',322),
  ('condition -> IDENTIFIER LESS_EQ NUMBER','condition',3,'p_condition','main.py',323),
  ('condition -> IDENTIFIER EQUALS value','condition',3,'p_condition','main.py',324),
  ('condition -> IDENTIFIER NOT_EQUALS value','condition',3,'p_condition','main.py',325),
  ('value -> STRING','value',1,'p_value','main.py',329),
  ('value -> NUMBER','value',1,'p_value','main.py',330),
  ('limit_clause -> LIMIT NUMBER','limit_clause',2,'p_limit_clause','main.py',334),
  ('limit_clause -> empty','limit_clause',1,'p_limit_clause','main.py',335),
  ('create_select_stmt -> CREATE TABLE IDENTIFIER select_stmt','create_select_stmt',4,'p_create_select_stmt','main.py',343),
  ('create_join_stmt -> CREATE TABLE IDENTIFIER FROM IDENTIFIER JOIN IDENTIFIER USING LPAREN IDENTIFIER RPAREN','create_join_stmt',11,'p_create_join_stmt','main.py',361),
  ('procedure_decl -> PROCEDURE IDENTIFIER DO program END','procedure_decl',5,'p_procedure_decl','main.py',427),
  ('procedure_call -> CALL IDENTIFIER','procedure_call',2,'p_procedure_call','main.py',433),
  ('empty -> <empty>','empty',0,'p_empty','main.py',441),
]
